#pragma once

#include <dwrite.h>


namespace GameEngine
{
	enum class DWriteFontStretch
	{
		UNDEFINED = DWRITE_FONT_STRETCH_UNDEFINED,
		ULTRA_CONDENSED = DWRITE_FONT_STRETCH_ULTRA_CONDENSED,
		EXTRA_CONDENSED = DWRITE_FONT_STRETCH_EXTRA_CONDENSED,
		CONDENSED = DWRITE_FONT_STRETCH_CONDENSED,
		SEMI_CONDENSED = DWRITE_FONT_STRETCH_SEMI_CONDENSED,
		NORMAL = DWRITE_FONT_STRETCH_NORMAL,
		MEDIUM = DWRITE_FONT_STRETCH_MEDIUM,
		SEMI_EXPANDED = DWRITE_FONT_STRETCH_SEMI_EXPANDED,
		EXPANDED = DWRITE_FONT_STRETCH_EXPANDED,
		EXTRA_EXPANDED = DWRITE_FONT_STRETCH_EXTRA_EXPANDED,
		ULTRA_EXPANDED = DWRITE_FONT_STRETCH_ULTRA_EXPANDED
	};
}
